# Generated by Django 3.2 on 2023-05-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("STUDENT", "Student"), ("SUPERVISOR", "Supervisor")],
                default=None,
                max_length=20,
                null=True,
            ),
        ),
    ]
