# Generated by Django 3.2 on 2023-05-09 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20230509_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='StudyYear',
        ),
    ]
