# Generated by Django 3.2 on 2023-05-09 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20230509_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supervisor',
            old_name='user',
            new_name='user1',
        ),
    ]
