# Generated by Django 3.2 on 2023-05-09 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0005_alter_token_user'),
        ('admin', '0005_alter_logentry_user'),
        ('accounts', '0010_rename_user_supervisor_user1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Supervisor',
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
        ),
    ]
